-- No-op.
--
-- The old global `system_config` table was removed in the profile-scoped cutover.
-- Keeping this file as a no-op preserves migration ordering for environments where
-- all SQL files are executed on each startup.
